#!/bin/bash

if [ $# -ne 2 ]
then
    echo "Потрібно передати два значення" >&2
    exit 1
fi

if ! [[ $1 =~ ^[0-9]+$ ]] || ! [[ $2 =~ ^[0-9]+$ ]]
then
    echo "Числа мають бути додатними та цілими" >&2
    exit 1
fi

tree_height=$1
snow_width=$2

if [ $tree_height -lt 3 ]
then
    echo "Висота ялинки має бути не меншою за 3" >&2
    exit 1
fi

if [ $snow_width -lt 3 ]
then
    echo "Ширина снігу має бути не меншою за 3" >&2
    exit 1
fi

branch_width=$((snow_width - 2))
tier_height=$(((tree_height - 2) / 2))
trunk_width=3
trunk_height=2

for (( tier = 0; tier < 2; tier++ )); do
    width=1
    i=0
    while [ $i -lt $tier_height ]
    do
        if [ $((i % 2)) -eq 0 ]
        then
            char="*"
        else
            char="#"
        fi
        spaces=$(((snow_width - width) / 2))
        printf "%*s" $spaces ""
        printf "%s\n" "$(printf "%${width}s" | tr ' ' "$char")"
        width=$((width + 2))
        i=$((i + 1))
    done

done

for trunk in trunk1 trunk2; do
    printf "%*s" $(((snow_width - trunk_width) / 2)) ""
    printf "%s\n" "$(printf "%${trunk_width}s" | tr ' ' "#")"
done

snow_layer=0
until [ $snow_layer -eq 1 ]
do
    printf "%s\n" "$(printf "%${snow_width}s" | tr ' ' "*")"
    snow_layer=1
done
